import type { AnalysisResult, Snapshot } from '@/types';

/**
 * Generates a clean markdown document summarising what the reader has read.
 * Intended for pasting or sharing into Gemini, ChatGPT, Claude, etc.
 */
export function buildShareMarkdown(
  bookTitle: string,
  bookAuthor: string,
  lastAnalyzedIndex: number,
  currentChapterTitle: string,
  totalChapters: number,
  result: AnalysisResult,
  snapshots: Snapshot[],
  chapterTitles: string[],
): string {
  const chaptersRead = lastAnalyzedIndex + 1;
  const lines: string[] = [];

  lines.push(`# Reading context: "${bookTitle}" by ${bookAuthor}`);
  lines.push('');
  lines.push(
    `> The reader has finished **chapter ${chaptersRead} of ${totalChapters}** ` +
    `("${currentChapterTitle}"). The summary below contains **no spoilers beyond that point**. ` +
    `Please answer questions based only on what is described here.`,
  );
  lines.push('');

  // --- Plot summary ---
  const sorted = [...snapshots].sort((a, b) => a.index - b.index).filter((s) => s.result.summary);
  if (sorted.length > 0) {
    lines.push('## Story so far (chapter by chapter)');
    lines.push('');
    for (const snap of sorted) {
      const title = chapterTitles[snap.index] ?? `Chapter ${snap.index + 1}`;
      lines.push(`**After "${title}":** ${snap.result.summary}`);
      lines.push('');
    }
  } else if (result.summary) {
    lines.push('## Story so far');
    lines.push('');
    lines.push(result.summary);
    lines.push('');
  }

  // --- Characters ---
  if (result.characters.length > 0) {
    lines.push('## Characters');
    lines.push('');
    for (const c of result.characters) {
      const parts: string[] = [`**${c.name}**`];
      parts.push(`(${c.importance}, ${c.status})`);
      if (c.currentLocation && c.currentLocation !== 'Unknown') parts.push(`— at ${c.currentLocation}`);
      if (c.recentEvents) parts.push(`— ${c.recentEvents}`);
      else if (c.description) parts.push(`— ${c.description.split('.')[0]}`);
      lines.push(`- ${parts.join(' ')}`);
    }
    lines.push('');
  }

  // --- Locations ---
  const locs = result.locations ?? [];
  if (locs.length > 0) {
    lines.push('## Locations');
    lines.push('');
    for (const l of locs) {
      lines.push(`- **${l.name}**: ${l.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by BookBuddy — spoiler-free reading companion*');

  return lines.join('\n');
}

/**
 * Shares or copies the markdown context.
 * Uses Web Share API on mobile (opens system share sheet), falls back to clipboard.
 * Returns 'shared', 'copied', or throws.
 */
export async function shareReadingContext(markdown: string, bookTitle: string): Promise<'shared' | 'copied'> {
  const canShare = typeof navigator !== 'undefined' && !!navigator.share;

  if (canShare) {
    try {
      await navigator.share({
        title: `Reading context: ${bookTitle}`,
        text: markdown,
      });
      return 'shared';
    } catch (err) {
      // User cancelled share sheet — don't fall through to clipboard
      if (err instanceof Error && err.name === 'AbortError') throw err;
      // Other error — fall through to clipboard
    }
  }

  await navigator.clipboard.writeText(markdown);
  return 'copied';
}
